name: gymbros
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  supabase_flutter: ^2.5.2
  flutter_secure_dotenv: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_secure_dotenv_generator: ^1.0.3

flutter:
  uses-material-design: true
